#!/usr/bin/env python3

# Copyright (c) 2011, Willow Garage, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the Willow Garage, Inc. nor the names of its
#      contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

from turtle import distance
import rospy
from geometry_msgs.msg import Twist
from markers import *
import os
import numpy as np



from nav_msgs.msg import Odometry
from tf.transformations import euler_from_quaternion, quaternion_from_euler


WAFFLE_MAX_LIN_VEL = 0.26
WAFFLE_MAX_ANG_VEL = 1.82

PLOTTING = True

msg = """
Running node
"""

e = """
Communications Failed
"""


x=0
y=0
x_d=0
y_d=0
phi=0
phi_d=0
t = 0
error = 0

POSITION_OUTPUT_FILE = os.path.dirname(os.path.realpath(__file__)) + "/data/position.txt"

#Subscriber functions
def on_odometry(msg):
  global x,y, phi, x_d, y_d, phi_d, t, error
  x = msg.pose.pose.position.x
  y = msg.pose.pose.position.y
  #phi = msg.pose.pose.orientation.z
  orientation_q = msg.pose.pose.orientation
  orientation_list = [orientation_q.x, orientation_q.y, orientation_q.z, orientation_q.w]
  (roll, pitch, yaw) = euler_from_quaternion(orientation_list)
  phi = yaw
  if PLOTTING == True:
    write_to_file(t, x_d, y_d, phi_d, x, y, phi, error)
  t+=1


# General functions
def clear_file(filename):
  file = open(filename,"w")
  file.close()


def write_to_file(t, xd, yd, phid, x, y, phi, error):

  with open(POSITION_OUTPUT_FILE, 'a') as file:
    file.write(str(t) + ", " + str(xd) + ", " + str(yd) + ", " + str(phid) + ", " + str(x) + ", " + str(y) + ", " + str(phi) + ", " + str(error) +"\n")
    file.close()
              
  #rospy.loginfo("Written positions")


def constrain(input, low, high):
    if input < low:
      input = low
    elif input > high:
      input = high
    else:
      input = input

    return input

def checkLinearLimitVelocity(vel):
    vel = constrain(vel, -WAFFLE_MAX_LIN_VEL, WAFFLE_MAX_LIN_VEL)
    return vel

def checkAngularLimitVelocity(vel):
    vel = constrain(vel, -WAFFLE_MAX_ANG_VEL, WAFFLE_MAX_ANG_VEL)
    return vel

def normalize_angle(angle):
  """
  Normalize an angle to [-pi, pi].
  :param angle: (float)
  :return: (float) Angle in radian in [-pi, pi]
  """
  if angle > np.pi:
      angle -= 2.0 * np.pi

  if angle < -np.pi:
      angle += 2.0 * np.pi

  return angle


# Main function
if __name__=="__main__":
    # Init node
    rospy.init_node('start_node')

    # Publishers  // rospy.Publisher('topic_name', MessageType, queue_size=10)
    pub = rospy.Publisher('cmd_vel', Twist, queue_size=10)

    # Subscribers  //  rospy.Subscriber('topic_name', MessageType, callback_function)
    rospy.Subscriber('odom', Odometry, on_odometry)

    # Declaration of Green marker
    bmarker = BallMarker(color['GREEN'])

    turtlebot3_model = rospy.get_param("model", "burger")
    
    # Init and clear files
    clear_file(POSITION_OUTPUT_FILE)
    

    # Loop rate (in Hz)
    rate = rospy.Rate(10)


    # Desired position and heading
    x_d = -0.2
    y_d = -0.2
    bmarker.xyz([x_d, y_d, 0.05])

    
    
    # Control Parameters
    Kp = 1.5
    Ki = 0.0
    Kd = 0.0

    # try:
    print(msg)
    while not rospy.is_shutdown():
        
        distance = np.abs(np.sqrt((y_d-y)**2+(x_d-x)**2))
        # Linear speed constant
        linear_vel = 0.2*distance #0.1 #0.15

        # PID implementation of orientation control
        phi_d = np.arctan2((y_d-y),(x_d-x))
        alpha= phi_d - phi
        #error = alpha
        error = np.arctan2(np.sin(alpha),np.cos(alpha))
        angular_vel =  Kp*(error)
  
        #angular_vel = 0.5

      

        
        twist = Twist()

        
        twist.linear.x = checkLinearLimitVelocity(linear_vel); twist.linear.y = 0.0; twist.linear.z = 0.0

        
        twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = checkLinearLimitVelocity(angular_vel)
        
        pub.publish(twist)
        bmarker.publish()
        
        if distance<0.01:
          break

        rate.sleep()
        

    # except:
    #     print(e)

    # finally:
    twist = Twist()
    twist.linear.x = 0.0; twist.linear.y = 0.0; twist.linear.z = 0.0
    twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = 0.0
    pub.publish(twist)
    